version: '3.9'

services:
  auth_api:
    image: ghcr.io/Sven491/XTransit/auth_api:latest
    container_name: auth_api
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER_AUTH}
      DB_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  employee_api:
    image: ghcr.io/Sven491/XTransit/employee_api:latest
    container_name: employee_api
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER_EMPLOYEE}
      DB_PASSWORD: ${POSTGRES_PASSWORD_EMPLOYEE}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  transit_api:
    image: ghcr.io/Sven491/XTransit/transit_api:latest
    container_name: transit_api
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER_TRANSIT}
      DB_PASSWORD: ${POSTGRES_PASSWORD_TRANSIT}
    restart: unless-stopped
